language: java
jdk:
- oraclejdk7
script:
- wget https://gist.githubusercontent.com/Nunnery/2716c87ed5657884fcc2/raw/2d7dcc0328a68eb624cdc13475834d179c24d255/settings.xml
- mvn clean deploy --settings settings.xml
env:
  global:
    secure: RDWZ/96QDCVgD7DaEdzUB6tTc+2OJPWpeS0NO+552hCT1kSZpnseAJkDSazj3FD2UyGkuVHpax5FsNokNl3Vla1NyC1Ym8XZpq4RUmOROOAJi3laD4edhMIRu7THMBC99SmVBCu3vHm3vjZlpEx5E4fIMe0+9tVhkJzFB3bUArQ=
notifications:
  slack:
    secure: QrN7MbVT3AtXrjuXwxPpz+B+pEycsze77GS9csLyDVOBTKilpetWLHwsRnzOxb28zlSGvsW027wnRSev70Hk1UatYlxtWtrkO/irRA3Gi5kJlOxkPVi9SuoPFWAH275fKTs9uxrZDdu7VLUqCcrO8E9XrW6wfOMDOxa+qdtzxiI=
