version: "0.0.2"
cells-per-member: 1
time-since-tagged-in-seconds: 5
guild-creation-price: 5000
perm-color:
  Owner: '§5'
  Administrator: '§4'
  Moderator: '§6'
  Cmod: '§b'
  Donator: '§e'
  Veteran: '§9'