name: @NAME@
version: @VERSION@
main: me.topplethenun.tribes.TribesPlugin
depend: [facecore, q]

commands:
  tribe:
    alias: [tr]

permissions:
  tribes.command:
    default: true
  tribes.command.create:
    default: op
  tribes.command.claim:
    default: true
  tribes.command.name:
    default: true
  tribes.command.invite:
    default: true
  tribes.command.validate:
    default: true