name: @NAME@
version: @VERSION@
main: com.tealcube.minecraft.bukkit.tribes.TribesPlugin
depend: [Facecore, Q, NametagEdit]

commands:
  tribe:
    alias: [tr]
  pvp:
    alias: []
  duel:
    alias: []

permissions:
  tribes.command:
    default: true
  tribes.command.create:
    default: op
  tribes.command.claim:
    default: true
  tribes.command.name:
    default: true
  tribes.command.invite:
    default: true
  tribes.command.validate:
    default: true
  tribes.command.top:
    default: true
  tribes.command.pvp:
    default: true